### ISSUE TITLE
Pie charts doesn't load if the reports shared through Jenkins.

### ISSUE THREAD

**Issue by praveenabraham21** [gkushang/cucumber-html-reporter#71] opened 2017-05-11 18:00 UTC
Thanks for the awesome cucumber html report. The report speaks for itself. 

The HTML report when viewed through Jenkins, pie chart load issue is observed.

This error message is displayed. Looking for your help on this. 

Invalid JSON string: {"width":"100%","height":240,"title":"10 Features","is3D":true,"colors":["#5cb85c","#d9534f","#999","#5bc0de","#428bca","#f0ad4e"],"fontSize":"13","fontName":"\"Helvetica Neue\", \"Helvetica\", Helvetica, Arial, sans-serif","slices":{"1":{"offset":0.4},"2":{"offset":0.4},"3":{"offset":0.4},"4":{"offset":0.4},"5":{"offset":0.4},"6":{"offset":0.4}},"titleTextStyle":{"fontSize":"13","color":"#5e5e5e"}}

**Comment by praveenabraham21** [comment] 2017-05-11 18:05
![jenkins_pie_chart_load](https://cloud.githubusercontent.com/assets/17757914/25964424/6fca1116-36a2-11e7-9746-7b0b61da349a.png)

**Comment by gkushang** [comment] 2017-06-02 18:20
@praveenabraham21 is this issue still reproducible?

**Comment by gkushang** [comment] 2017-06-05 17:55
@praveenabraham21 

I'll close this issue since it has been quite inactive for while.

Please feel free to reopen and to give feedback if something comes up.

Thanks!

**Comment by praveenabraham21** [comment] 2017-07-12 11:53
@gkushang: Hi Kushang, Yes this is reproducible. Please have a look. I shared the cucumber html report through Jenkins, so that remote users can view the results in my machine. They don't get the chart representation of the features and scenarios result. An invalid JSON format error is displayed.  

Attaching a screenshot of the how report looks. 
![issue_screenshot](https://user-images.githubusercontent.com/17757914/28116346-5bc2e42c-6726-11e7-9660-130fb059273b.png)

**Comment by gkushang** [comment] 2017-07-12 14:39
@praveenabraham21 

It seems more like an issue with the `"fontName":""Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif"` where it's unable to retain double quotes, String. However, I am unable to reproduce the issue locally (might be restricted to Jenkins), so cannot test the change.

My strong guess is to updating the fontName might fix it - `fontName: 'Helvetica Neue',` 

I've made the above change to branch **`issue/71`**. Would you be able to help us test the change within your Jenkins?  If so, you'd need to commit the below change in your _**package.json**_, and try running the smoke tests again,

`"cucumber-html-reporter": "git://github.com/gkushang/cucumber-html-reporter.git#issue/71",`

Let us know what you get. 

Thanks!

**Comment by praveenabraham21** [comment] 2017-07-13 15:31
Hi @gkushang : 
Thanks, I tested with this new branch, changing the fontName doesn't work. This issue seems to be not related to cucumber-html-reporter. 

My Jenkins is causing it seems. Someone faced a similar issue from Jenkins. 
https://stackoverflow.com/questions/34740963/missing-pie-chart-and-other-elements-when-display-serenity-report-from-jenkins

I am trying to sort out the Jenkins security policy to resolve this. Let me know if you come across any thing on this. 
https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

Thanks again.

**Comment by gkushang** [comment] 2017-07-13 15:50
Got it. Thanks for getting back to us 👍 

Closing the issue since it's related to content security on Jenkins.

**Closed by gkushang** 2017-07-13 15:50 UTC
